### ISSUE TITLE
App needs a back end.

### ISSUE THREAD

**Issue by svanardenne** [svanardenne/mental_health_app#2]
Create a server folder and initialise an express app in it.

**Comment by jnutt367** [comment]
index.js needs to be refactored,
but I did install these dependencies for our server side
* body-parser = allows us to send POST requests.
* cors =  cross origin resource sharing.
* express = Using as a framework for creating the routing of application.
* mongoose = Creates a model for posts.
* nodemon = keeps me from having to restart the server by myself. It automates the server.
